//
// Country.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Country: Codable { 

    public var country: String?
    public var countryCode: String?
    public var slug: String?
    public var newConfirmed: Int?
    public var totalConfirmed: Int?
    public var newDeaths: Int?
    public var totalDeaths: Int?
    public var newRecovered: Int?
    public var totalRecovered: Int?
    public var date: String?

    public init(country: String?, countryCode: String?, slug: String?, newConfirmed: Int?, totalConfirmed: Int?, newDeaths: Int?, totalDeaths: Int?, newRecovered: Int?, totalRecovered: Int?, date: String?) {
        self.country = country
        self.countryCode = countryCode
        self.slug = slug
        self.newConfirmed = newConfirmed
        self.totalConfirmed = totalConfirmed
        self.newDeaths = newDeaths
        self.totalDeaths = totalDeaths
        self.newRecovered = newRecovered
        self.totalRecovered = totalRecovered
        self.date = date
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case country = "Country"
        case countryCode = "CountryCode"
        case slug = "Slug"
        case newConfirmed = "NewConfirmed"
        case totalConfirmed = "TotalConfirmed"
        case newDeaths = "NewDeaths"
        case totalDeaths = "TotalDeaths"
        case newRecovered = "NewRecovered"
        case totalRecovered = "TotalRecovered"
        case date = "Date"
    }

}
