//
// SummaryGlobal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SummaryGlobal: Codable { 

    public var newConfirmed: Int?
    public var totalConfirmed: Int?
    public var newDeaths: Int?
    public var totalDeaths: Int?
    public var newRecovered: Int?
    public var totalRecovered: Int?

    public init(newConfirmed: Int?, totalConfirmed: Int?, newDeaths: Int?, totalDeaths: Int?, newRecovered: Int?, totalRecovered: Int?) {
        self.newConfirmed = newConfirmed
        self.totalConfirmed = totalConfirmed
        self.newDeaths = newDeaths
        self.totalDeaths = totalDeaths
        self.newRecovered = newRecovered
        self.totalRecovered = totalRecovered
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case newConfirmed = "NewConfirmed"
        case totalConfirmed = "TotalConfirmed"
        case newDeaths = "NewDeaths"
        case totalDeaths = "TotalDeaths"
        case newRecovered = "NewRecovered"
        case totalRecovered = "TotalRecovered"
    }

}
